{% set name = "iotop" %}
{% set version = "1.30" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Tomas-M/iotop/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 862e3d3d0263e4171aa9c5aaed2dd7d76ca746afa58ecbb6eca002717e9fa240

build:
  skip: true  # [not linux]
  script: make && make install PREFIX=$PREFIX && mv $PREFIX/sbin/iotop $PREFIX/bin/iotop
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
  host:
    - ncurses

test:
  commands:
    - $PREFIX/bin/iotop --version

about:
  home: https://github.com/Tomas-M/iotop
  summary: 'A top utility for IO'
  description: |
    iotop identifies processes that use high amount of input/output requests on your machine. It is similar to the well known top utility, but instead of showing you what consumes CPU the most, it lists processes by their IO usage.
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - matthiasdiener
