{% set name = "iotop" %}
{% set version = "1.28" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Tomas-M/iotop/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b83e5c7d82da3bfb3e46b74e91b24a52fc65d44ff268ace95b613972e27fc678

build:
  skip: true  # [not linux]
  script: make && make install PREFIX=$PREFIX && mv $PREFIX/sbin/iotop $PREFIX/bin/iotop
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make
  host:
    - ncurses

test:
  commands:
    - $PREFIX/bin/iotop --version

about:
  home: https://github.com/Tomas-M/iotop
  summary: 'A top utility for IO'
  description: |
    iotop identifies processes that use high amount of input/output requests on your machine. It is similar to the well known top utility, but instead of showing you what consumes CPU the most, it lists processes by their IO usage.
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: LICENSE

extra:
  recipe-maintainers:
    - matthiasdiener
