github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  error_overlinking: true
conda_forge_output_validation: true
test: native_and_emulated
provider:
  linux_ppc64le: default
  linux_aarch64: default
